import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <fieldset>
          <legend>Formulário</legend>
          <form action="https://formspree.io/f/xayaljzg" method="POST">
            <label htmlFor="name">Nome:    </label>
            <input type="text" name="name" id="name" />
            <br/>
            <label htmlFor="cpf">CPF:    </label>
            <input type="text" name="cpf" id="cpf" /> <p>utilizamos o cpf para validar junto a receita federaal a sua identidade</p>
            <br/>
            <label htmlFor="idade">Idade:    </label>
            <input type="number" name="idade" id="idade" />
            <p>Este serviço só pode ser acessado por maiores de 17 anos, por isso precisamos armazenar a sua idade</p>
            <br/>
            {/* utilizando gênero personalizado */}
            <label htmlFor="genero">Gênero:    </label>
            <select name="genero" id="genero">
              <option value="masculino">Masculino</option>
              <option value="feminino">Feminino</option>
              <option value="outro">Outro</option>
            </select>
            <p>Opcional, não precisamos do gênero, mas se for informado o serviço será customizado para você</p>
            <br/>
            <p>A proteção de dados é nossa prioridade. Para obter mais informações 
              </p><p>sobre como trataremos os seus dados, clique aqui para acessar a nossa política de privacidade</p>
            <button type="submit">Enviar</button>
          </form>
        </fieldset>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
